dcs/action.py
dcs/condition.py

This uses lua serializer dumps to correctly output arguments for trig rules inline lua code. 
Primary error was that string arguments for conditions were serialized without quotes, but I find some another places that could potentially bring the same issue.

trig rules lua serialization syntax fixed

---

dcs/task.py

Subject. 
I haven't found any docs on "unitId" in those tasks, but it seems that without it they would simply not work.
Stennis seems to use system 3 rather than 4, so I've added the aa argument to support both.

ICLS + TACAN update

---

dcs/action.py
dcs/unitgroup.py

I don't know whether this is by design, but it does seem counter intuitive anyway.
+ that dumps update

Remove previous loadout before loading new one

---

dcs/__init__.py
dcs/countries.py
dcs/helicopters.py
dcs/nav_target_point.py
dcs/planes.py
dcs/ships.py
dcs/unitgroup.py
dcs/vehicles.py
dcs/weapons_data.py
tests/test_mission.py

Hello, 
I ran a data export for my own usage, for the new Supercarrier module support.
I have been using it for a day, and it's working fine.
**Note:** After running the export, I had to manually remove a "planes.F_4E_new" reference that was being added in countries.py, while this plane did not exist in planes.py. Looks like a new F_4E model is coming in the game, but might be currently disabled.
Thanks, 
Khopa

data-export: version 2.5.6.49798

---

dcs/countries.py
dcs/planes.py
dcs/ships.py
dcs/terrain/normandy.py
dcs/vehicles.py
dcs/weapons_data.py

The airport dump for Normandy had not been made since the last map update in late 2019 iirc.
See https://github.com/pydcs/dcs/issues/50
I ran a new airport dump and added the missing airports.
I noticed :
- a lot of changes to runway directions, parking slots positions... etc
- The name of the Ford base has changed. (Now "Ford AF" instead of "Ford")
***
I also jumped on the occasion to make a new data-export to add the few units that were added in the very last open beta.
By analyzing the new export, i noticed that:
- Deka added a new Chinese ship  (Type 071)
- Deka changed the id for almost all their ships. (I'm worried about compatibility issues.)
- There are more possible payloads for the JF-17 
- ED added a new MLRS unit

Added Normandy missing airbases + data-export 2.5.6.52196

---

dcs/task.py
dcs/unitgroup.py

Hello @rp- 
I made this branch to add the "manualHeading" parameter. This is this parameter in DCS mission editor, that is only available for ground units : 
This allow forcing the heading of a unit regardless of its waypoints.
I also made some small changes to some "Option" tasks, and completed some Enums.
Thanks,
Khopa

Add manual heading

---

dcs/flyingunit.py
dcs/unitgroup.py
tests/test_mission.py

One behavioral change here that is present even without using the new
API: channel 1 of radio 1 will no longer be forcibly set during
serialization. It will still be set when set_frequency() is called,
but this allows callers to set their own channel 1 for radio 1 as
desired. DCS (the mission editor, at least) will automatically set
channel 1 of the first compatible radio to the flight's frequency, but
that is not necessarily the first radio (such as for an F-16 with a
VHF flight channel).

Add support for setting preset radio channels.

---

dcs/action.py

DCS Liberation currently has an issue where generated missions need to be opened in the mission editor and saved before delayed flights behave properly. I'm not completely sure that either of these changes fixes that issue (I can't reproduce it myself), but these seem to be the only two behavioral differences in the mission file before and after saving with the mission editor. They do seem to be incorrect, although it's possible these are working due to some default behavior for each function.

Reduce differences between DCS and pydcs mission files.

---

dcs/vehicles.py
tools/pydcs_export.lua

Hello,
There was a small typo in the exported eplrs variable name for ground vehicles.
This commit should fix it.
Thanks, 
Khopa

Fixed typo in "EPLRS" variable export for ground vehicles

---

dcs/action.py
tests/test_mission.py

Hello
I added support for two missing mission editor actions : 
* Scenery Destruction Zone
* Scenery Remove Objects Zone
Regards,
Khopa

Added support for scenery destruction zone, and remove scene objects actions

---

dcs/countries.py
dcs/helicopters.py
dcs/planes.py
dcs/ships.py
dcs/statics.py
dcs/vehicles.py
dcs/weapons_data.py
tests/test_mission.py
tools/pydcs_export.lua

Data export for DCS version 2.5.6.57264
It mainly adds a few new units that were added in the WW2 asset pack : 
* M1 37mm AAA
* M45 quadmount AAA
* QF 3.7-inch AAA
* Daimler Armoured Car
* M4 High-Speed Tractor
* Light Tank Mk VII Tetrarch
* FuMG 401 Freya LZ radar
I had to modify the pydcs export script, because of the display name of the QF_17 gun containing the '"' character.

data-export: 2.5.6.57264

---

dcs/planes.py
tools/pydcs_export.lua

Here is a small fix : The SpitfireLFMkIXCW module was not seen as a flyable module.

Fix : SpitfireLFMkIXCW not interpreted as flyable

---

dcs/terrain/terrain.py

When not passing a coalition to nearest_airport, self.airports was being
used exactly rather than only its values.

Fix nearest_airport when coalition is None.

---

dcs/forcedoptions.py

Adds the following missing options:
* Unrestricted SATNAV
* Wake turbulence
* Cockpit status bar
* Battle damage assessment
* User marks
Adds an enum for the labels option.
Fixes the name of the immortal option, but adds a property to preserve
source compatibility.
Removes the following unused options:
* Scenes
* Tips
I did not preserve source compatibility for the removed options, because
callers that are expecting that to do something should adapt their code.
Even so, writers of these values will still be able to write them.

Add missing entries to `ForcedOptions`. Add types.

---

dcs/coalition.py

In lua points are stored as a dict not an array and the order can get messed up(which is not a problem as it is keyed). I suspect it is using string sorting so if there are more then 10 WPs the order gets messed up when the mission is loaded back([1, 10, 11, 12, 2, ...]). This change fixes the issue.

Fix waypoint order when loading from miz

---

dcs/cloud_presets.py
dcs/weather.py
tests/test_weather.py
tools/weather_import.py

In 2.7 cloud presets can be selected, which will:
* Override cloud thickness, density, and precipitation
* Bound the cloud base
* Set the "preset" property in the mission file
This patch adds an import script to load the names and cloud base
boundaries from the config file in the DCS install. The script requires
lupa because the parser in dcs.lua is not capable of parsing complex lua
files (I think it's because there are function calls, but I didn't dig
much).
This also removes the `Weather.fog_density` property, since DCS no
longer supports that.
Fixes https://github.com/pydcs/dcs/issues/118

Support DCS 2.7 cloud presets.

---

dcs/country.py
dcs/flyingunit.py

Resolves #122 
Respects the original data type of onboard_num while still allowing uniquely generated tail numbers.
Ran all unit tests before and after making this change with no discrepancies.
I've only recently picked up Python after 7-8 years of years since I last touched it, please do tell me if there's something I haven't done or confirmed.

Respect original data type of onboard_num

---

dcs/mission.py

I've experienced an issue whereby any exceptions at the time of serialization when saving result in an existing .miz archive becoming corrupt as no mission file is written.
This proposed change moves the serialization of the `options`, `warehouse` and `mission` objects to outside the processing of the mission archive. This prevents any corruption from happening and allows the exception to bubble up without modifying the mission.
This won't affect missions that are created via pydcs, such as Liberation, but does resolve corruption issues for any missions that are loaded via `load_file` and re-saved.
I've also removed some commented code that I saw as I was just making this change.

Serialize objects prior to overwriting the .miz zip

---

dcs/countries.py
dcs/planes.py
dcs/ships.py
dcs/statics.py
dcs/vehicles.py
dcs/weapons_data.py

Hello, 
I ran the data-export for today new openbeta version, in order to support the newly added units :
- PT-76
- АА-7,2-60 FireFighter - Ural 4332
- ATZ-5 - Ural 4320
- Diesel power station 5i57A
- VAB Mephisto
- Chieftain Mk.3
- La Combattante II (ship)
- Leopard 2A5
- Leopard 2A6M (replaced Leopard-2)
- Leopard 2A4
- Leopard 2A4TR (Turkey)
- Seawise Giant (ship)
- SPH T-155 Fırtına
Khopa

data-export 2.7.1.6430

---

dcs/task.py

Not sure when this got added to DCS, but multirole fighters are a
separte target type now.
The task also emits a `value` field in addition to `targetTypes` that is
the same thing but a semicolon delimited list.
The ME also produces a `noTargetTypes` which is like `targetTypes`,
but for all the things that *weren't* selected. I've omitted that since
it doesn't seem to matter.

Add multirole fighters target option.

---

dcs/condition.py

Adds support for the `c_missile_in_zone` condition and also fixes a formatting issue with `c_bomb_in_zone` which caused the condition to be serialized as a key-value pair instead of a string joined by dots.
Before:
```
[42]="return(c_bomb_in_zone({[1]=4,[2]=5,[3]=36,[4]=38}, 1, 59) or c_bomb_in_zone({[1]=4,[2]=5,[3]=9,[4]=31}, 1, 59) or c_bomb_in_zone({[1]=4,[2]=5,[3]=9,[4]=32}, 1, 59) or c_bomb_in_zone({[1]=4,[2]=5,[3]=36,[4]=281}, 1, 59) )",
```
After:
```
[42]="return(c_bomb_in_zone(\"4.5.36.38\", 1, 59) or c_bomb_in_zone(\"4.5.9.31\", 1, 59) or c_bomb_in_zone(\"4.5.9.32\", 1, 59) or c_bomb_in_zone(\"4.5.36.281\", 1, 59) )",
```

Add support for MissileInZone with correct condition formatting

---

dcs/mission.py
dcs/unit.py

Hi, I started to write a new mission tool using `pydcs` and couldn't find the new invisible FARP. So I added it. I also added a new `farp_type` parameter to `Mission.farp`. This lets you change the farp type by passing a class reference. I moved it to the end so that it hopefully doesn't cause any conflicts with the existing code.
Here is a small sample script that generates a mission with one instance of each farp type:
~~~ python
import dcs
mission = dcs.Mission(dcs.terrain.Syria())
hatay = mission.terrain.hatay()
usa = mission.country("USA")
mission.farp(country=usa,
name="FARP 1",
position=dcs.Point(hatay.position.x + 1000, hatay.position.y + 1000),
)
mission.farp(country=usa,
name="FARP 2",
position=dcs.Point(hatay.position.x + 2000, hatay.position.y + 1000), …

Add invisible FARP

---

dcs/mission.py
dcs/point.py
dcs/unittype.py
setup.py

These commits together are the errors I found while updating Liberation to type check our uses of pydcs. In one case there was an actual bug (loading a mission with a refuel/rearm landing waypoint and then resaving it would corrupt the mission by writing a string back where an integer was needed).
This also adds the py.typed file, without which mypy ignore type annotations in this package when checking dependents: https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

Fix incorrect type annotations, add py.typed.

---

dcs/weather.py

From testing through Liberation, DCS appears to accept float values just fine.
If mmHg is an integer, there is poor resolution. For example the inches Hg value of 29.94 would not be possible to have. Next up from 29.92 would be 29.96.

Use floats for qnh and temperature

---

dcs/flyingunit.py

Instead of silently returning, when clearly the operation did not complete with success.

Raise TypeError when not possible to set radio channels

---

dcs/terrain/caucasus.py
dcs/terrain/nevada.py

The failure on p file loading was causing issues when building a python project with pydcs into an exe file. This PR solves it.
Considering that the city_graph objects are not widely used in pydcs, I think it would be preferrable to fail only when the p files are actually needed. That way you can use pydcs as a library without the p files, as long as you don't use the destroy_oil_transport.py code.

Dont fail so soon when p graph files are not found

---

dcs/lua/serialize.py
tests/test_serialize.py

Initial scenario: use PyDCS to open a Mission file, perform small manipulation and then re-save the file.
If the contents of the `mission` file is placed under source code control (unzip and placed under git), various elements would be rearranged and generate noise on diffs.
Consider the following original order:
```
{
[1] = a,
[2] = b,
...
[9] = c,
[10] = d
}
```
When `pydcs` performs the `mission.save()` method call, the order in the `mission` file would be:
```
{
[1] = a,
[10] = d,  # <---- notice this
[2] = b,
...
[9] = c
}
```
The problem becomes harder if there is something added at index before `10` would generate a bunch of noise. In the reshuffle (consider `c`).
```
{
[1] = a,
[10] = c, # I'm "new green" even though just changed position
[11] = d,
[2] = b,
...
[9] = …
```

Preserve index array for integer based key dictionaries

---

dcs/unitgroup.py

Ground-spawned aircraft can have their heading set, and if pydcs doesn't respect that it will rewrite the heading to point towards the first waypoint, when editing a mission file.
I'm not sure if this is the most elegant way to do this. I don't fully understand the code. These spawn types are not defined in any constants in the code.
Before open/save:
After saving with pydcs (first aircraft has been manually corrected):

Use manual heading for ground spawned aircraft

---

dcs/drawing/layer.py
tests/test_drawings.py

Used to draw things like these:
This is technically a helper function. But it's a common primitive in air tasking maps. And I suspect DCS will add it to the standard primitives sometime in the future, upon which we can change this code to use that instead. So I believe it belongs in the layer class.

Add support for oblong drawing

---

dcs/countries.py
dcs/planes.py
dcs/weapons_data.py
tools/pydcs_export.lua

Includes Viper ECM, radio config change for the Viggen, and a bunch of new callsigns for a few US jets.
The first commit fixes the export script to work for the latest DCS. The second is the data.

Data export for DCS 2.7.9.17830.

---

dcs/condition.py

This adds the c_dead_zone triggerrule condition which allows to check if a mapobject was killed. Plan is to use this triggerrule to handle killed map objects in dcs liberation.
With the DCS Patch 2.7 ED renamed the UI Name for the condition within the MissionEditor from `DEAD_ZONE` to `MAP OBJECT IS DEAD`. Thats why i gave the class the name MapObjectIsDead instead of DeadZone which is not really meaningful
Source: https://www.reddit.com/r/hoggit/comments/mrc8oy/psa_map_objects_now_have_dedicated_trigger/

Add MapObjectIsDead TriggerRule Condition

---

dcs/task.py

If the Option.Value has a Enum with a 0 value, the option does not get correctly written to the mission file.
Examples include OptROE.Values.WeaponsFree and OptECMUsing.Values.NeverUse.

Correct value check in Option.

---

dcs/task.py

I feel like I took an unconventional approach to this when compared to all the other Option Tasks.
DCS has a different formation format for rotary aircraft than fixed wing aircraft.  Some formations have extra options, some do not.
Because there are three different values for each formation, I chose to use static methods be the main method of generating these formations.
Wasn't sure if it was possible/how to test this in the existing tests, so I only tested it by incorporating it into DCS Liberation and checking if the values of the formations I used looked right.
Let me know if you disagree with stuff.  I wasn't sure if I should put `airplane` or `fixed_wing` in front of the fixed wing only options like I did with `rotary`.
This is the mission I made to source the data (changed extension …

Adding OptFormation Data

---

dcs/flyingunit.py
dcs/unit.py

In order to enable setting custom liveries to ground units in addition to aircraft, moved livery_id from FlyingUnit class to parent Unit class.

Support for ground vehicle liveries

---

dcs/mapping.py

A common case I'm finding is that I need to take the X/Y coordinates of
a point, use them in another system (such as shapely), then convert the
result back into a Point. I'm currently doing that by accessing the
(supposedly private) _terrain member. This adds a less invasive method
for doing that.

Add Point API for creating new Points.

---

dcs/unit.py

It seems this property is no longer used in the latest miz version.
Fixes https://github.com/pydcs/dcs/issues/214

Remove the transportable property from units.

---

dcs/task.py

AttackGroup was missing some params which were already added to other tasks. So i copy pasted the params from the AttackUnit task while checking which DCS adds by default and whats the default value. You can see the task object created from the mission editor with just default settings:
So the changes match them.
Also add the missing "All" value for the Expand Param

Update AttackGroup task with missing params

---

dcs/countries.py
dcs/helicopters.py
dcs/planes.py
dcs/task.py
dcs/vehicles.py
dcs/weapons_data.py

Support for the new open beta patch https://www.digitalcombatsimulator.com/en/news/changelog/openbeta/2.7.12.23362/
PR includes:
- Data export
- New ACLS and Link4 taskings
Changes in the data export:
Adds new vehicles (Technicals), Fixes wrong liveries and adds new ones, changed some weapon data.
~I will test the PR real quick with Liberation before marking it as ready for review (until then i will let it draft)~

Support for DCS 2.7.12.23362

---

setup.py

Without this change, PyDCS cannot be used with poetry.
Python's [documentation ](https://docs.python.org/3/distutils/setupscript.html#listing-whole-packages) states:
> (Keep in mind that although `package_dir` applies recursively, you must explicitly list all packages in packages: the Distutils will not recursively scan your source tree looking for any directory with an `__init__.py` file.)
It seems that when installing with `pip`, this limitation doesn't apply. However, when using [Poetry](https://python-poetry.org/) (and possibly other Python package managers?), this limitation is honored. So `dcs.terrain.projections` is never installed, which causes `import dcs` to fail.

Add terrain.projections package to setup.py

---

setup.py

In #231 I added the `terrain.projections` package to `setup.py`. Unfortunately I missed the fact that there is a `drawing` package that needs to be added as well. This PR adds that to the `package` list in `setup.py` as well.

Add drawing package to setup.py (missed in #231)

---

dcs/action.py
tests/test_mission.py

This attribute seems to be unused in prior versions of DCS, and now no longer added by the mission editor.
Should fix #207.

Remove all mentions of `meters` from scenery actions

---

tools/pydcs_export.lua

When trying to export data, DCS stays stuck at 10% and the logs provide the following error:
ALERT   Dispatcher: Error starting Game GUI: [string "_path_to_pydcs_\tools\pydcs_export.lua"]:844: attempt to concatenate field '?' (a nil value)
This ought to fix the issue, and I also noticed a `file:close()` was missing for ships so I threw that in as well.

Fix for ship export in pydcs_export.lua

---

dcs/helicopters.py

For some reason the export doesn't recognize the Mi-24P as flyable on my end. Maybe because I don't have the module installed?
One thing's for sure, it should be flyable...

Export didn't include Mi-24P as flyable

---

dcs/planes.py
tools/pydcs_export.lua

Re-organized the flyables by type (jet engine/piston engine/helicopter) which makes verification a little easier, and sorted them alphabetically. Ran another export to be sure.
Two things I'd like to elaborate:
- Most of the additions in the flyables map don't have any effect, since it was already being exported correctly, I simply added them just to guarantee it stays exporting the flyable types correctly.
- I changed `F/A-18C` into `FA-18C_hornet`, since the former is referring to the AI model. Either way, the hornet (flyable one) was already being exported correctly so this simply removes the "flyable" option for the AI version.

Fix Flyables

---

dcs/terrain/terrain.py
dcs/unittype.py

I ran into a little mistake I made regarding the default livery. 
The 'name' is what's shown in DCS' mission editor, the (path) 'id' is what we need for mission generation.
When liberation can't determine a livery for a squadron, it'll use `default_livery` as a fallback at some point, causing missing textures because of a wrong 'livery_id' in the mission file.

Fix mistake in 'default_livery'

---

dcs/liveries_scanner.py

The code looks right (it's doing utf-8 decoding where expected), but a
user is reporting an issue that seems to be a wrongly encoded livery. We
can safely skip these, but log them so it's clear why they aren't
available.
https://github.com/dcs-liberation/dcs_liberation/issues/2368

Catch and log unicode errors in liveries.

---

dcs/liveries_scanner.py

I seems to have forgotten to initialize the Liveries in the stub-generator.
Aside from that I also realized "zipped liveries" need to account for different encodings, so I refactored out part of the previous solution #248 in order to make it reusable for reading description files within zip-files.

Add encoding support for zipped liveries + initialize Liveries in stub-generator

---

dcs/triggers.py

A conversation was started in #243 explaining why this PR is needed.
In short, we need the `radius` in the base-class `TriggerZone` in order to serialize the mission correctly. The second commit adds a polymorphic method `is_point_in_zone` that returns `True` if a given point is inside the zone, `False` otherwise.
For a circular trigger zone this is pretty straight forward, but for quad-points that was a little trickier. I think I provided enough comments in the code to explain what's happening, but feel free to point out if something else is worth mentioning.

Triggers: Re-expose radius

---

dcs/terrain/caucasus/airports.py
dcs/terrain/falklands/airports.py
dcs/terrain/marianaislands/airports.py
dcs/terrain/nevada/airports.py
dcs/terrain/normandy/airports.py
dcs/terrain/persiangulf/airports.py
dcs/terrain/syria/airports.py
dcs/terrain/terrain.py
dcs/terrain/thechannel/airports.py
tools/airport_import.py

The existing code was working for some maps, but the code that skipped the opposite heading sides of the same physical runway was dependent on the ordering of the runway names. For airports that had both a left and right runway, this resulted in two indistinguishable runways.
I've also removed the unset `ils` and `leftright` properties (ILS will be making a comeback once we have beacon data), and added additional data from the lua dump.

Fix runway data for some maps.

---

dcs/condition.py

Copy/Paste from the PartOfCoalition Condition to add the missing unit type parameter which can be set in the mission editor:

Add missing UnitType to AllOfCoalition in/out zone conditions

---

dcs/unit.py
tests/test_mission.py

Prior to this change, PyDCS would remove custom smoke effect attributes, effectively resetting all of their sizes to the default effect.
This change adds optional fields that appear for smoke effect in-game static objects.

Don't delete effect presets for smoke effects

---

setup.py

these directories were recently added, and because they were not in the `packages` listing in `setup.py`, were not being correctly added into the distribution package.
this PR fixes the issue and makes git installs work again.
fixes #283

correct packages listing in `setup.py`

---

dcs/task.py

I'm not totally sure how this works yet, but `onStartMission` allows troops in the Embarking zone to be loaded when the mission starts, rather than for the helicopter to takeoff and then land to pickup.
replicates this option in the mission editor:

add onStartMission option for Embarking task

---

dcs/terrain/falklands/airports.py
tools/airport_import.py

It doesn't seem like we can safely ignore airports even if they appear to be broken. The ME will include every airport ID in the warehouses file of the miz, and we shouldn't ignore errors from that file, so we do need to have a record of every airport the game reports, even if the data is potentially bogus.
See https://github.com/dcs-liberation/dcs_liberation/issues/2732.

Fix terrain export for Falklands and update.

---

dcs/terrain/terrain.py
tests/test_terrain.py

Some airfields such as Tbilisi in Caucuses and Aleppo in Syria have Heli only slots, these slots are currently being occupied by normal airplanes due to `terrain.py` not taking Heli only slots into account. This causes planes to start in air and crash immediately at mission start.
This fix adds the check and some tests to make sure airplanes don't spawn in Heli only slots

Fixed issue with airplanes trying to spawn on heli slots

---

dcs/liveries_scanner.py

Before this patch, if this file is corrupt (or the format changes in a way pydcs doesn't expect), pydcs will crash on import since the livery scanner runs at import time.

Ignore parse errors in Liberation prefs.

---

dcs/installation.py
dcs/winreg.py
tests/test_installation.py

Querying the registry in each caller made the test mocks quite messy. Factor that out so we can clean up the implementation and the tests. This also removes the "is standalone" and "is steam" APIs since those don't seem useful and they complicated the implementation. The other cleanup this makes easy is switching to the contextmanager OpenKey, which fixes the bug I found when writing the test in the previous PR.

Factor out wingreg usage to simplify.

---

dcs/payloads.py

File I/O during import is bad. This kind is particularly annoying because the DCS directory discovery only works on Windows machines with DCS installed.

Make payload directory loading lazy.

---

dcs/lua/parse.py
dcs/lua/test_parse.py

Probably not done yet. This fixes a handful of bugs (and adds missing features) necessary for parsing liveries lua descriptions.

Many lua parser fixes.

---

dcs/lua/parse.py
dcs/lua/test_parse.py

`--]]` is just a convention, apparnelty. `]]` is what actually ends the block.

Fix bug in block comment parsing.

---

dcs/liveries/livery.py
tests/liveries/test_livery.py

Experimentally via the ME this appears to be required.

Force livery IDs to lower case.

---

dcs/countries.py
dcs/country.py
tests/test_country.py
tools/pydcs_export.lua

The livery code works with short names, so we need a lookup for that. I'm not sure if the full names are stable or not but I'd added that until proven otherwise as well.

Export more country mappings.

---

dcs/liveries/livery.py

Make the livery parser tolerant of its own failures. Our lua parser is not robust enough to have failures be fatal since DCS can arbitrarily push an update that will find our bugs. I've added an xfail test for the new failure case, but haven't implemented the fix in the parser.

Livery parser fix.

---

dcs/helicopters.py
dcs/planes.py
dcs/unitpropertydescription.py
dcs/unittype.py
tools/pydcs_export.lua

There's a lot of additional data available in the lua database that informs any callers how to implement the UI. Expose that in the unit type as well.
I've added this as a new API surface rather than extending the data in the old API which is only queryable via reflection. The old API is good for hard-coded mission generators that want to set properties explicitly, but for anyone trying to create a UI for setting these (such as Liberation does), it's preferable to have access without reflection.

Export additional unit property info.

---

dcs/flyingunit.py

Whatever properties were set last would apply to all aircraft of the same type because this was copied by reference.

Fix all same type aircraft sharing properties.

---

dcs/ships.py

This adds the carrier ARA Veinticinco de Mayo, which is misspelled in DCS as the Vienticinco.

Data export for DCS 2.8.7.42718 (adds ARA Veinticinco de Mayo)

---

dcs/task.py

There's some nuance to this that's called out in the changelog (https://www.digitalcombatsimulator.com/en/news/changelog/openbeta/2.9.0.46801/):
> NEW: Advanced Waypoint Action for Unlimited Fuel Option for AI. Please
> note the task must be at the top of Advanced Waypoint Actions list to
> make sure it works properly.
I've got no idea if that's a bug in the current implementation or if that's always going to be how it is. In any case, I haven't handled it directly here. It'll be up to the caller to make sure they prepend rather than append this task.

Add support for the new unlimited fuel command.

---

dcs/mapping.py
tests/test_mapping.py

The other type this is compared to might not be Point, and that shouldn't raise an error. It's often a programming mistake to write that comparison, but there's a way to run into this without the caller having a bug: comparing two instances of a dataclass with an `Point | None` member where the rhs has None and the lhs has a Point.

Fix AttributeError in Point.__eq__.

---

dcs/action.py
dcs/drawing/drawing.py
tools/actions_export.py

I goofed when force pushing https://github.com/pydcs/dcs/pull/344 and pushed pydcs/master to that branch instead of my local HEAD. Doing that automatically closed the PR since it no longer had any new commits in it, and because there's no longer a PR from that branch I can't force push to it any more. Reuploading.

Reupload of #344

---

dcs/planes.py
dcs/weapons_data.py

This includes new AIM-9s and rockets for the F-16, and JSOW for the F-15E.
The M-2000 no longer has some of the properties for configuring LGB codes and gun/rocket ripple settings which looks odd, but the mission editor agrees. Those are configurable via the kneeboard in cockpit so I suppose razbam doesn't think they're needed any more.
There are some other changes as well but those are the highlights.

Data export for DCS 2.9.2.49629 Open Beta.

---

dcs/task.py

Fix for WeaponType.Auto. 9663676414 noticed when using WWII units, Big Formation, Carpet Bombing.

Fix for WeaponType.Auto

---

dcs/mission.py
tests/test_mission.py

Mission.load_file() uses a check for "pictureFileNameN" since old mission files might not have it defined.

Support for briefing pictures for neutral side

---

dcs/action.py
tools/actions_export.py

resolves error when mission contains a wait-for-user action using "flag_back"

renamed flag_black to proper name flag_back

---

dcs/password.py
dcs/unitgroup.py

* Password is not base64 encoded, but base64URL encoded. Missed that in the initial read.

Fix for setting password for Unit Groups

---

dcs/countries.py
dcs/helicopters.py
dcs/weapons_data.py
tools/pydcs_export.lua

This PR updates the DCS export for 2.9.5.55918 to support the Kiowa Warrior.

DCS Export for 2.9.5.55918

---

dcs/mission.py
dcs/terrain/terrain.py

With DCS2.9.6, a warehouse is needed for aircraft to spawn on carriers and FARPs. This change in DCS means the following trivial example missions would fail:
```
from dcs.mission import Mission
from dcs.ships import Stennis, HarborTug
from dcs.planes import FA_18C_hornet
from dcs.helicopters import Mi_8MT
from dcs import countries  
from dcs import mapping
from dcs import unit
mission = Mission()
blue = mission.country("USA")
sg = mission.ship_group(blue, "Carrier", Stennis, mapping.Point(-200000, 450000, mission.terrain))
ag = mission.flight_group_from_unit(blue, "Player", FA_18C_hornet, sg)
ag.units[0].skill = unit.Skill.Player
mission.save("carrier_spawn.miz")
mission = Mission()
blue = mission.country("USA")
farp = mission.farp(blue, "FARP", mapping.Point(-284879, 636819, …
```

Fix spawns on carriers and FARPs in DCS 2.9.6

---

dcs/task.py

This PR fixes a typo which prevents UnitPayloads for F4E being loaded as an AFAC task is used.

Fix typo leading to failure when parsing payloads

---

dcs/mission.py
dcs/terrain/terrain.py

This PR updates the population of warehouses to add the `allowHotStart` key and uses ints instead of strings as unit IDs. These changes affected multiplayer missions where units spawned on carriers / FARPs.
Without these changes, the following will generate a .miz file that works fine for single player but does not allow spawning in multiplayer.
```
from dcs.mission import Mission
from dcs.ships import Stennis, HarborTug
from dcs.planes import FA_18C_hornet
from dcs.helicopters import Mi_8MT
from dcs import countries  
from dcs import mapping
from dcs import unit
mission = Mission()
blue = mission.country("USA")
sg = mission.ship_group(blue, "Carrier", Stennis, mapping.Point(-200000, 450000, mission.terrain))
ag = mission.flight_group_from_unit(blue, "Player", FA_18C_hornet, sg) …
```

Fix carrier and FARP spawns in multiplayer

---

dcs/mission.py
dcs/task.py
dcs/weather.py

This patch focuses solely on typo fixes found during review.
- `dcs/mission.py`, line 1354: `referene` → `reference`
- `dcs/mission.py`, line 1358: `frequencey` → `frequency`
- `dcs/mission.py`, line 1410: `referene` → `reference`
- `dcs/mission.py`, line 1414: `frequencey` → `frequency`
- `dcs/task.py`, line 1: `specifiy` → `specify`
- `dcs/task.py`, line 969: `exaclty` → `exactly`
- `dcs/task.py`, line 1876: `Seperation` → `Separation`
- `dcs/weather.py`, line 181: `visiblity` → `visibility`
Functionality remains unchanged.

Fixed non-functional documentation typos
