dcs/unit.py
Mission loading was failing on Warehouse/Tank.
=> Changed canCargo for statics to optional parameters for mission loading

dcs/condition.py
=> Implement UnitAltitude AGL conditions for triggers

dcs/countries.py, dcs/helicopters.py, dcs/planes.py, dcs/ships.py, dcs/weapons_data.py
Data export for version 2.5.5.40647
(To support the new JF-17 module)
=> data-export: version 2.5.5.40647

dcs/coalition.py, dcs/mission.py, dcs/terrain/terrain.py
=> Fix old mission time

dcs/countries.py, dcs/helicopters.py, dcs/mission.py, dcs/planes.py, dcs/terrain/__init__.py, dcs/terrain/syria.py, dcs/weapons_data.py, tests/test_mission.py, tools/airport_import.py
Hello @rp-, 
I made the airport dump for the new Syria map and integrated it in pydcs.
I also ran a data export for the newest DCS openbeta version (2.5.6.53756).
This add the Chinese WingLoong-I drone and East Germany as a new country)
Khopa
=> Syria map update

dcs/unittype.py
[Khopa/dcs_liberation#153](https://github.com/Khopa/dcs_liberation/issues/153)
[pydcs/dcs#77](https://github.com/pydcs/dcs/issues/77)
=> fix issue #77 and Khopa/dcs_liberation#153

dcs/action.py, dcs/condition.py, dcs/goals.py, dcs/triggers.py, tests/test_triggers.py
There were problems with Or conditions, wrong ResourceKey
identifier and smaller indention problems.
Closes #89
=> fix and test trig dict generation

dcs/task.py
Also annotated some missing types.
=> Fix type for EngageTargetInZone constructor.

dcs/countries.py, dcs/planes.py
Hello, 
This is the data-export for latest DCS version. (Which include a new F-14A variant)
Khopa
=> data-export 2.5.6.57949

dcs/terrain/syria.py
Hi, 
In a recent update, it seems like ED pushed many fixes to the Syria map, changing parking slots position, and adding new ones.
So i ran a new data export of the map airfield data.
Khopa
=> Syria terrain update

dcs/countries.py, dcs/helicopters.py, dcs/planes.py, dcs/statics.py, dcs/vehicles.py, dcs/weapons_data.py, tools/pydcs_export.lua
Data export for the new open beta version.
The following ground units ZSU-57, BTR-82, T72B3 were added
=> data-export 2.5.6.59398

dcs/unitgroup.py
Added 'hiddenOnPlanner', 'hiddenOnMFD' to Groups
#88
=> Added 'hidden_on_planner' and 'hidden_on_mfd' to unitgroup

dcs/point.py
Added the new PointAction "LandingReFuAr"
Added a check when reading the key "task" from dictionary. This caused problems when using SAM templates.
=> Point.py | fix error in load_from_dict and added PointAction LandingReFuAr

dcs/coalition.py, dcs/translation.py, dcs/unitgroup.py
Missions saved from DCS 2.7 seem to not translate group names.
=> Handle untranslated group names.

dcs/forcedoptions.py
=> New neutral dot label support

dcs/point.py
This is the "time" property in the ME for this type of waypoint.
=> Add support for LandReFuAr time property.

dcs/flyingunit.py, dcs/task.py
Added added the basic SetCallsign command and put it in the wrappedactions dict. Don't know if there's a list of ground-unit-only commands this shoulod be entered in too somewhere.
=> Added SetCallsign command

dcs/action.py, dcs/flyingunit.py, dcs/task.py
Adds support for
* Action: a_zone_increment_resize
* Task: FAC_AttackGroup (#58)
I've also changed the Helicopter FlyingUnit so that `ropeLength` is optional as it seems to be optional in some mission files.
=> Add missing action and task support

dcs/terrain/syria.py
New terrain export for the updated Syria map (many fixes to parking slots were implemented in the new version, and now including new airfields on Cyprus island.)
=> terrain-export 2.7.2.7910 for syria map

.github/workflows/pythonpackage.yml, dcs/mission.py, dcs/terrain/__init__.py, dcs/terrain/marianaislands.py, tools/airport_import.py
The in-game theater is `MarianaIslands` with no plural on `Mariana` so I re-named everything to match
=> Fixing names for Mariana Islands (was previously MarianaS Islands)

dcs/mission.py
=> Correct signature of Mission.add_resource_file.

.github/workflows/pythonpackage.yml, setup.py
Fixes https://github.com/pydcs/dcs/issues/162.
=> Drop Python 3.6 support. Test Python 3.9.

dcs/countries.py, dcs/planes.py, dcs/ships.py, dcs/vehicles.py, dcs/weapons_data.py
This DCS update will probably need map exports too, but I haven't figured those out yet.
=> Export latest data for DCS 2.7.4.9632.

dcs/templates.py
Minor update to fix issues with using the site templates.
=> Update SA-11 and SA-6 Templates to match actual units

dcs/flyingunit.py, dcs/unitgroup.py, tests/test_mission.py
=> Prevent failures when setting radio presets by checking for radio

dcs/countries.py, dcs/helicopters.py, dcs/planes.py, dcs/statics.py, dcs/vehicles.py, dcs/weapons_data.py
Hello, 
Here is the data update for the latest DCS openbeta (2.7.6.12852). 
This adds : 
* MosquitoFBMkVI
* SA-5 (S-200)
* H-6J 
Also multiple update to weapons data.
Regards,
Khopa
=> Data update for version 2.7.6.12852

dcs/planes.py, tools/pydcs_export.lua
Hello,
In my latest data-export, i forgot to export the Mosquito as a flyable module, this PR fixes this.
Regards,
Khopa
=> Fixed Mosquito not being marked as flyable

dcs/task.py
=> Add Disembarking task

dcs/scripts/nevada_random_mission.py, dcs/terrain/caucasus.py, dcs/terrain/marianaislands.py, dcs/terrain/nevada.py, dcs/terrain/persiangulf.py, tests/test_terrain.py
Caucasus, Mariana, Nevada and PG had some updates since the last export
Biggest change here is the rename of nearly all Nevada Airports.
I do not own the WW2 maps so i cant not create an export for them.
=> Terrain update (from DCS 2.7.9.18080)

dcs/terrain/terrain.py
The transformers are not pickleable. Make them cached properties so they
aren't serialized.
=> Make Terrain picklable again.

dcs/terrain/syria.py
Adds the new airports from DCS 2.7.11.21408.1.
=> Terrain data update for Syria.

dcs/countries.py, dcs/helicopters.py, dcs/planes.py, dcs/vehicles.py, dcs/weapons_data.py, tools/pydcs_export.lua
This includes a few other fixes needed to keep export working with the new version.
=> Data export for DCS 2.7.11.21408.1.

dcs/helicopters.py, dcs/planes.py, dcs/weapons_data.py
Mostly livery updates, plus a few weapon changes.
=> Data export for DCS 2.7.14.24228.

dcs/countries.py, dcs/helicopters.py, dcs/planes.py, dcs/ships.py, dcs/statics.py, dcs/vehicles.py, dcs/weapons_data.py, tests/test_mission.py, tools/pydcs_export.lua
This is a PR with an export only, 2 things had to change for this:
- Some Apache weapons have names with semi-colons in them, they need to be removed
- Tests needed adjustments since the 'VINSON' is becoming obsolete, replaced it with 'Stennis'
Merging #236 will make this PR obsolete since it also includes an export...
=> Export 2.7.16

dcs/liveries_scanner.py
https://github.com/dcs-liberation/dcs_liberation/issues/2368
Reverts commit 2a7230db48dd21495d05d52c905b88cb2b34b883 in the process.
=> Support ANSI description files in livery scanner

dcs/triggers.py
Reverts pydcs/dcs#251
Should not have been submitted yet. GitHub UI failed me.
=> Revert "Triggers: Re-expose radius"

dcs/mission.py, dcs/terrain/falklands.py
New terrain update, and handle falklands miz files when loading from file.
=> Falklands updates.

dcs/atcradio.py, dcs/terrain/caucasus.py, dcs/terrain/falklands.py, dcs/terrain/marianaislands.py, dcs/terrain/nevada.py, dcs/terrain/normandy.py, dcs/terrain/persiangulf.py, dcs/terrain/syria.py, dcs/terrain/terrain.py, dcs/terrain/thechannel.py, tools/airport_import.py
https://github.com/pydcs/dcs/issues/69
=> Include ATC radio frequencies in airport info.

dcs/beacons.py, dcs/terrain/__init__.py, dcs/terrain/caucasus/airports.py, dcs/terrain/falklands/airports.py, dcs/terrain/marianaislands/airports.py, dcs/terrain/nevada/airports.py, dcs/terrain/normandy/airports.py, dcs/terrain/persiangulf/airports.py, dcs/terrain/syria/airports.py, dcs/terrain/terrain.py, dcs/terrain/thechannel/airports.py, tools/airport_import.py
These mappings alone aren't very useful, but it's also possible to extract the data for each beacon so we can associate these IDs with TACAN and ILS info.
https://github.com/pydcs/dcs/issues/69
=> Preserve beacon information in Airport and Runway.

dcs/helicopters.py, tools/pydcs_export.lua
https://github.com/pydcs/dcs/issues/266
=> Skip UI labels in property export.

dcs/action.py, dcs/lua/parse.py, dcs/mapping.py, dcs/mission.py, dcs/scripts/nevada_random_mission.py, dcs/stub templates/liveries_scanner.pyi, dcs/task.py, dcs/terrain/terrain.py
Noticed this was missing, solution's pretty much the same as any other boolean option
=> Add option to jettison empty tanks

dcs/planes.py, dcs/terrain/caucasus/airports.py, dcs/terrain/falklands/airports.py, dcs/terrain/marianaislands/airports.py, dcs/terrain/nevada/airports.py, dcs/terrain/normandy/airports.py, dcs/terrain/persiangulf/airports.py, dcs/terrain/syria/airports.py, dcs/terrain/thechannel/airports.py
Includes a lot of new airports in the Falklands (and a lot of updated ATC data).
=> Data and terrain export for DCS 2.8.0.33006.

dcs/weather.py
Ice Halos were added in DCS 2.8.  The new mission behavior in DCS is to have Halos set to "Auto" by default.
=> Add Ice Halo support

dcs/task.py
Add support for the new RecoveryTanker task.
=> Add RecoveryTanker to tasks.

dcs/country.py, dcs/mission.py, tests/test_mission.py
This allows the user to more naturally customize attributes of vehicle group members.
Added test cases for group creation.
=> Add method for creating vehicle groups by list of Vehicle objects

dcs/triggers.py
Hi,
I added the ability to set a color for a trigger.
See this in action here:
=> added color to triggers

dcs/countries.py, dcs/planes.py, dcs/ships.py, dcs/weapons_data.py
Includes the new A-10C radios.
=> Data export for DCS 2.8.3.37556.

dcs/terrain/normandy/airports.py
Lots of new airports, a bunch of updated ATC data.
=> Normandy 2 export.

.github/workflows/pythonpackage.yml, setup.py
Past EOL.
Fixes https://github.com/pydcs/dcs/issues/299.
=> Drop Python 3.7 support.

dcs/task.py
Doesn't seem to work otherwise.
=> Put SetUnlimitedFuelCommand in wrappedactions dict

dcs/planes.py, dcs/weapons_data.py
=> Data export for DCS 2.9.1.48111 Open Beta.

dcs/terrain/falklands/airports.py, dcs/terrain/normandy/airports.py
Updates for Normandy and South Atlantic.
=> Terrain export for DCS 2.9.1.48111 Open Beta.

dcs/task.py
Imitated the bombing task and just adjusted the parameters. Appears to work well for both deserialization and serialization in my manual test.
=> Add strafing task

dcs/mission.py
=> fixed "noon" random_daytime preset

dcs/terrain/caucasus/airports.py, dcs/terrain/falklands/airports.py, dcs/terrain/normandy/airports.py, dcs/terrain/syria/airports.py, tools/airport_import.py
* Ran airport_import.py for the following terrains:
- normandy
- thechannel
- caucasus
- falklands
- marianaislands
- nevada
- persiangulf
- syria
=> DCS-2.9.3.51704: airport data updates

dcs/countries.py, dcs/helicopters.py, dcs/planes.py, dcs/ships.py, dcs/vehicles.py, dcs/weapons_data.py
DCS data export for version 2.9.4.53627 (post hotfix).
=> DCS export for 2.9.4.53627 (post hotfix)

dcs/terrain/falklands/airports.py, dcs/terrain/normandy/airports.py
* Terrains processed:
- caucasus
- marianaislands
- normandy
- syria
- falklands
- nevada
- persiangulf
- thechannel
=> Imported airport data for 2.9.9.24740
